{
 "title": "Asterisk Dashboard Full",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(asterisk_bridges_count{instance=~\".*\"}, instance)\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://www.asterisk.org/wp-content/uploads/asterisk-logo.png\"\n     alt=\"Asterisk Icone\"\n     style=\"float: left; margin: 10px;\" />\n\n \n           "
   }
  },
  {
   "title": "Asterisk Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Asterisk core Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_core_uptime_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Asterisk core last reload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_core_last_reload_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Asterisk core scrape time (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_core_scrape_time_ms{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Simultaneous Active Calls / Channels / Bridges Historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "asterisk_calls_count{instance=\"$instance\"}"
    },
    {
     "expr": "asterisk_channels_count{instance=\"$instance\"}"
    },
    {
     "expr": "asterisk_bridges_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current Active Calls",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_calls_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max  Calls over the day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(asterisk_calls_count{instance=\"$instance\"}[1d])"
    }
   ]
  },
  {
   "title": "Current Active Channels",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_channels_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Channels over the day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(asterisk_channels_count{instance=\"$instance\"}[1d])"
    }
   ]
  },
  {
   "title": "Current Active Bridges",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_bridges_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Bridges over the day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(asterisk_bridges_count{instance=\"$instance\"}[1d])"
    }
   ]
  },
  {
   "title": "Current online  Endpoints",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(asterisk_endpoints_state{instance=\"$instance\"}==2)"
    }
   ]
  },
  {
   "title": "Max Endpoints over the day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(count(asterisk_endpoints_state{instance=\"$instance\"}==2)[1d:10m])"
    }
   ]
  },
  {
   "title": "Endpoints Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Online Endpoints Historical",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(asterisk_endpoints_state{instance=\"$instance\"}==2)"
      }
     ]
    },
    {
     "title": "Current Endpoints State ( 0=unknown; 1=offline; 2=online)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(asterisk_endpoints_state{instance=\"$instance\"}==0)\n",
       "legendFormat": "Enpoints Unknown"
      },
      {
       "expr": "count(asterisk_endpoints_state{instance=\"$instance\"}==1)",
       "legendFormat": "Endpoints Offline"
      },
      {
       "expr": "count(asterisk_endpoints_state{instance=\"$instance\"}==2)",
       "legendFormat": "Endpoint Online"
      }
     ]
    },
    {
     "title": "Current Defined Endpoints",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "asterisk_endpoints_count{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Historical  Endpoints Detail (Numbered of / Channels used over the period)",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 28 },
     "targets": [
      {
       "expr": "asterisk_endpoints_channels_count{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Evolution of Defined Endpoints",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "asterisk_endpoints_count{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Calls Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Simultaneous Active Calls / Channels / Bridges Historical",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "asterisk_calls_count{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total Calls since activation of metrics",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "asterisk_calls_sum{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max simultaneous Active Calls over the last year",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 4, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(asterisk_calls_count{instance=\"$instance\"}[1y])"
      }
     ]
    },
    {
     "title": "Number of calls over the last hour",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 9, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(rate(asterisk_calls_sum{instance=\"$instance\"} [1h])*3600)"
      }
     ]
    }
   ]
  },
  {
   "title": "Channels Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Channels Historical",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "asterisk_channels_count{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Current Channels State  (0=down; 1=reserved; 2=offhook; 3=dialing; 4=ring; 5=ringing; 6=up; 7=busy; 8=dialing_offhook; 9=prering.)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(asterisk_channels_state{instance=\"$instance\"}==6)",
       "legendFormat": "Channels up"
      },
      {
       "expr": "count(asterisk_channels_state{instance=\"$instance\"}==0)\n",
       "legendFormat": "Channels down"
      },
      {
       "expr": "count(asterisk_channels_state{instance=\"$instance\"}==1)",
       "legendFormat": "Channels reserved"
      },
      {
       "expr": "count(asterisk_channels_state{instance=\"$instance\"}==2)",
       "legendFormat": "Channels offhook"
      },
      {
       "expr": "count(asterisk_channels_state{instance=\"$instance\"}==3)",
       "legendFormat": "Channels dialings"
      },
      {
       "expr": "count(asterisk_channels_state{instance=\"$instance\"}==4)",
       "legendFormat": "Channels ring"
      },
      {
       "expr": "count(asterisk_channels_state{instance=\"$instance\"}==5)",
       "legendFormat": "Channels ringing"
      },
      {
       "expr": "count(asterisk_channels_state{instance=\"$instance\"}==7)",
       "legendFormat": "Channels busy"
      },
      {
       "expr": "count(asterisk_channels_state{instance=\"$instance\"}==8)",
       "legendFormat": "Channels dialing_offhook"
      },
      {
       "expr": "count(asterisk_channels_state{instance=\"$instance\"}==9)",
       "legendFormat": "Channels prering"
      }
     ]
    },
    {
     "title": "Historical Individuals Channels Detail (0=down; 1=reserved; 2=offhook; 3=dialing; 4=ring; 5=ringing; 6=up; 7=busy; 8=dialing_offhook; 9=prering.)",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 30 },
     "targets": [
      {
       "expr": "asterisk_channels_state{instance=\"$instance\"}"
      },
      {
       "expr": "asterisk_channels_duration_seconds{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bridges Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Briges Historical",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "asterisk_bridges_count{instance=\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}